package com.example.trackerapp.db

import android.graphics.Bitmap
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "running_table") //table name
data class Run(
    var image: Bitmap? = null,
    var timestamp: Long = 0L, //When run was
    var avgSpeedInKMH: Float = 0f,
    var distanceInMeters: Int = 0,
    var timeInMillis: Long = 0L, //Who long the run was
    var caloriesBurned: Int = 0
) {
    @PrimaryKey(autoGenerate = true) //Id and uniqueness generated by ROOM
    var id: Int? = null
}